name: Download JetBrains Plugin from Direct Link

on:
  workflow_dispatch:
    inputs:
      download_url:
        description: 'Enlace directo de descarga del plugin (.zip)'
        required: true
        default: 'https://plugins.jetbrains.com/plugin/download?rel=true&updateId=...'
      plugin_name:
        description: 'Nombre amigable para el archivo (ej. my-plugin)'
        required: true
        default: 'jetbrains-plugin'

jobs:
  download-plugin:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar información de descarga
        run: |
          echo "Descargando plugin desde: ${{ github.event.inputs.download_url }}"
          echo "Nombre del plugin: ${{ github.event.inputs.plugin_name }}"

      - name: Crear nombre de archivo seguro
        id: filename
        run: |
          SAFE_NAME=$(echo "${{ github.event.inputs.plugin_name }}" | sed 's/[^a-zA-Z0-9_-]/_/g')
          FILE_NAME="${SAFE_NAME}.zip"
          echo "filename=$FILE_NAME" >> $GITHUB_OUTPUT
          echo "base_name=$SAFE_NAME" >> $GITHUB_OUTPUT

      - name: Descargar plugin desde enlace directo
        run: |
          DOWNLOAD_URL='${{ github.event.inputs.download_url }}'
          OUTPUT_FILE='${{ steps.filename.outputs.filename }}'
          
          echo "Descargando desde: $DOWNLOAD_URL"
          curl -L -o "$OUTPUT_FILE" "$DOWNLOAD_URL" --fail

          if [ $? -ne 0 ]; then
            echo "❌ Falló la descarga del plugin desde $DOWNLOAD_URL"
            exit 1
          fi

          echo "✅ Plugin descargado como $OUTPUT_FILE"
          ls -lh "$OUTPUT_FILE"

      - name: Verificar que es un archivo ZIP válido
        run: |
          FILE='${{ steps.filename.outputs.filename }}'
          if ! unzip -t "$FILE" > /dev/null 2>&1; then
            echo "❌ El archivo descargado no es un ZIP válido"
            exit 1
          fi
          echo "✅ El archivo es un ZIP válido"

      - name: Subir plugin como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.filename.outputs.base_name }}
          path: ${{ steps.filename.outputs.filename }}
          retention-days: 7
